name: "Fill README"

on:
  push:
    branches:
      - master

jobs:
  fill:
    name: "✨ Fill"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Set up Node"
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7.25.0

      - name: Set PNPM store path
        run: "echo \"PNPM_STORE_PATH=$(pnpm store path)\" >> $GITHUB_ENV"

      - name: Cache PNPM packages
        uses: actions/cache@v4
        with:
          path: ${{ env.PNPM_STORE_PATH }}
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      - name: "Install dependencies"
        run: "pnpm install"

      - name: "Fill README"
        run: "pnpm fill"

      - name: "Commit to git"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update latest blog post
          branch: master
          commit_author: Actions <actions@github.com>

