name: "Fill README"

on:
  push:
    branches:
      - master

jobs:
  fill:
    name: "✨ Fill"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Set up NodeJS v16"
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: "Install dependencies"
        run: "yarn"

      - name: "Fill README"
        run: "yarn fill"

      - name: "Commit to git"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update latest blog post
          branch: master
          commit_author: Actions <actions@github.com>

